micronaut:
  application:
    name: sipService
netty:
  default:
    allocator:
      max-order: 3

eureka:
  client:
    registration:
      enabled: true
    defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"
