"component: backend":
  - Services/**/*
"component: ui":
  - frountend/**/*
"status: waiting-for-triage":
  - ./*
  - ./**/*
"type: documentation": docs/**/*
"type: dependency-upgrade":
  - Services/**/pom.xml