"component: backend":
  - changed-files:
      - any-glob-to-any-file:
          - services/**/*
"component: ui":
  - changed-files:
      - any-glob-to-any-file:
          - frountend/**/*
"type: documentation": 
  - changed-files:
      - any-glob-to-any-file: 'docs/**/*'
"type: dependency-upgrade":
  - changed-files:
      - any-glob-to-any-file:
          - services/**/pom.xml
