version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db/mongo
    ports:
      - 27017:27017
    networks:
      - investment-network
  
  zipkin-server:
    image: openzipkin/zipkin
    mem_limit: 512m
    expose:
      - "9411"
    ports:
      - "9411:9411"
    networks:
      - investment-network
      
volumes:
  mongo-data:
  
networks:
  investment-network: