eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
info:
  app:
    description: '@project.description@'
    name: '@project.name@'
  version: '@project.version@'
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      base-path: /${spring.application.name}
  health:
    circuitbreakers:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      default:
        failureRateThreshold: 90
server:
  port: 8085
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: '@project.artifactId@'
  cloud:
    gateway:
      routes: '[{id=sip-service, uri=http://localhost:8084/sip-service, predicates=[Path=
        /sip/**]}, {id=stock-service, uri=http://localhost:8083/stock-service, predicates=[Path=
        /stock/**]}]'
  data:
    mongodb:
      database: auth_db
      host: localhost
      port: 27017
zakura:
  app:
    jwtExpirationMs: 600000
    jwtSecret: zakuraSecretKey
