name: Angular CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: cd frontend && npm install && cd -
      - run: cd frontend && npm test
      - run: cd frontend && npm install -g @angular/cli > /dev/null
      - run: cd frontend && ng build --prod --output-path=dist --base-href="https://rajadileepkolli.github.io/investment-profile/" 
