# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven for Discovery Service

on:
  push:
    branches: [ master ]
    paths:
      - "services/discovery-service/**"
  pull_request:
    branches: [ master ]
    paths:
      - "services/discovery-service/**"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]
    defaults:
      run:
        working-directory: "services/discovery-service"

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3.11.0
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'zulu'
        cache: 'maven'

    - name: Build with Maven for API gateway
      run: ./mvnw -B package --file pom.xml

    - if: ${{ github.ref == 'refs/heads/master' }}
      name: Build and Publish Docker Image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=${{ secrets.DOCKER_USERNAME }}/discovery-service
        docker push ${{ secrets.DOCKER_USERNAME }}/discovery-service

    - name: Codecov
      uses: codecov/codecov-action@v3.1.4